export const temples = [
  {
    title: "Temple of Stillness",
    href: "/temples/stillness",
    icon: "/icons/temple-stillness.svg",
    image: "https://images.pexels.com/photos/7676886/pexels-photo-7676886.jpeg",
    content: "The Primordial Void: Depth and  the inner shadow",
    Bgcolor: "#111111",
    textColor: "#FFFFFF",
  },
  {
    title: "Temple of Purification",
    href: "/temples/purification",
    icon: "/icons/temple-purification.svg",
    image: "https://images.pexels.com/photos/6195987/pexels-photo-6195987.jpeg",
    content: "Purity: fluid release and the ritual of water",
    Bgcolor: "#FAF9F6",
    textColor: "#000000",
  },
  {
    title: "Temple of Return",
    href: "/temples/return",
    icon: "/icons/temple-return.svg",
    image: "https://images.pexels.com/photos/6559901/pexels-photo-6559901.jpeg",
    content: "Alchemical Love: radiance and golden intimacy.",
    Bgcolor: "#D4AF37",
    textColor: "#000000",
  },
  {
    title: "Temple of Voyage",
    href: "/temples/voyage",
    icon: "/icons/temple-voyage.svg",
    image:
      "https://images.pexels.com/photos/37180114/pexels-photo-37180114.jpeg",
    content: "Vital Growth: lush horizons and new frontiers ",
    Bgcolor: "#0F766E",
    textColor: "#FFFFFF",
  },
  {
    title: "Temple of Remembrance",
    href: "/temples/remembrance",
    icon: "/icons/temple-remembrance.svg",
    image: "/images/story-img1.webp",
    content: "Sovereign Lineage: ancestry and spiritual memory",
    Bgcolor: "#5B21B6",
    textColor: "#FFFFFF",
  },
  {
    title: "Temple of Belonging",
    href: "/temples/belonging",
    icon: "/icons/temple-belonging.svg",
    image:
      "https://images.pexels.com/photos/31433821/pexels-photo-31433821.jpeg",
    content: "Cosmic Depth: connection through the shared soul.",
    Bgcolor: "#1E40AF",
    textColor: "#FFFFFF",
  },
];
