import { Group } from "./definations";

// ─── Mock Data ────────────────────────────────────────────────────────────────
export const mockUser = {
  name: "Amara",
  avatar: "A",
};

export const mockGroups: Group[] = [
  {
    id: 1,
    name: "Gentle Grief Circle",
    category: "Grief & Loss",
    facilitator: "Dr. Nadia Osei",
    facilitatorTitle: "Certified Grief Counsellor",
    description:
      "A compassionate space for those navigating loss. Together we hold each other's stories without judgment, finding solace in shared experience and collective healing.",
    schedule: "Every Tuesday",
    time: "7:00 PM – 8:30 PM EAT",
    nextSession: "2026-06-10T19:00:00",
    format: "Video Call",
    members: 14,
    maxMembers: 18,
    status: "active",
    color: "#C8A882",
    icon: "🕊",
    tags: ["Grief", "Loss", "Community"],
    joined: "2026-03-15",
    sessionsAttended: 9,
    totalSessions: 12,
    upcomingTopics: ["Navigating anniversaries", "Letters to the departed"],
    resources: ["Grief journal template", "Self-compassion audio"],
  },
  {
    id: 2,
    name: "Inner Child Healing",
    category: "Emotional Healing",
    facilitator: "Kezia Mwangi",
    facilitatorTitle: "Somatic Therapist",
    description:
      "Reconnect with the younger parts of yourself that still need love and attention. Through guided imagery and gentle dialogue, we reparent with tenderness.",
    schedule: "Every Thursday",
    time: "6:00 PM – 7:30 PM EAT",
    nextSession: "2026-06-12T18:00:00",
    format: "Video Call",
    members: 11,
    maxMembers: 15,
    status: "active",
    color: "#A8C4B8",
    icon: "🌱",
    tags: ["Inner Child", "Reparenting", "Somatic"],
    joined: "2026-04-02",
    sessionsAttended: 6,
    totalSessions: 8,
    upcomingTopics: ["Play as medicine", "Boundaries as self-love"],
    resources: ["Inner child letter prompts", "Grounding breathwork audio"],
  },
  {
    id: 3,
    name: "Awakening Mothers",
    category: "Maternal Wellness",
    facilitator: "Sade Afolabi",
    facilitatorTitle: "Perinatal Wellness Coach",
    description:
      "A sacred circle for mothers on the spiritual and emotional journey of motherhood — before, during, and long after. No performance, only presence.",
    schedule: "Every Saturday",
    time: "10:00 AM – 11:30 AM EAT",
    nextSession: "2026-06-14T10:00:00",
    format: "Video Call",
    members: 16,
    maxMembers: 20,
    status: "upcoming",
    color: "#D4A5A5",
    icon: "🌸",
    tags: ["Motherhood", "Postpartum", "Spirituality"],
    joined: "2026-05-20",
    sessionsAttended: 2,
    totalSessions: 3,
    upcomingTopics: ["Releasing the 'perfect mother' myth"],
    resources: ["Postpartum affirmation cards"],
  },
];
