import { SupportGroup } from "./definations";

// ─── Mock Data ────────────────────────────────────────────────────────────────
export const mockUser = {
  name: "Amara",
  avatar: "A",
};
export const mockSupportGroups: SupportGroup[] = [
  {
    id: 1,
    name: "Gentle Grief Circle",
    category: "Grief & Loss",
    facilitator: "Dr. Nadia Osei",
    facilitatorTitle: "Certified Grief Counsellor",
    tagline: "You don't have to carry this alone.",
    description:
      "A compassionate space for those navigating the landscape of loss. We hold each other's stories without judgment, finding solace in shared experience. Whether your grief is fresh or years old, there is room for you here.",
    schedule: "Every Tuesday",
    time: "7:00 – 8:30 PM EAT",
    nextSession: "Tuesday, 10 June",
    format: "Video Call",
    duration: "90 min",
    members: 14,
    maxMembers: 18,
    status: "active",
    color: "#C8A882",
    secondaryColor: "#8B6A44",
    icon: "🕊",
    tags: ["Grief", "Loss", "Bereavement", "Community"],
    joined: "2026-03-15",
    sessionsAttended: 9,
    totalSessions: 12,
    price: "free",
    upcomingTopics: ["Navigating anniversaries", "Letters to the departed"],
    resources: ["Grief journal template", "Self-compassion audio"],
    level: "All are welcome",
  },
  {
    id: 2,
    name: "Inner Child Healing",
    category: "Emotional Healing",
    facilitator: "Kezia Mwangi",
    facilitatorTitle: "Somatic Therapist",
    tagline: "Return to yourself with tenderness.",
    description:
      "Reconnect with the younger parts of yourself still waiting to be seen and loved. Through guided imagery, gentle dialogue, and somatic awareness, we reparent ourselves with the care we always deserved.",
    schedule: "Every Thursday",
    time: "6:00 – 7:30 PM EAT",
    nextSession: "Thursday, 12 June",
    format: "Video Call",
    duration: "90 min",
    members: 11,
    maxMembers: 15,
    status: "filling",
    color: "#A8C4B8",
    secondaryColor: "#5A8A7A",
    icon: "🌱",
    tags: ["Inner Child", "Reparenting", "Somatic", "Trauma"],
    joined: "2026-04-02",
    sessionsAttended: 6,
    totalSessions: 8,
    price: "free",
    upcomingTopics: ["Play as medicine", "Boundaries as self-love"],
    resources: ["Inner child letter prompts", "Grounding breathwork audio"],
    level: "All are welcome",
  },
  {
    id: 3,
    name: "Awakening Mothers",
    category: "Maternal Wellness",
    facilitator: "Sade Afolabi",
    facilitatorTitle: "Perinatal Wellness Coach",
    tagline: "A sacred space for the mothers you truly are.",
    description:
      "For mothers on the spiritual and emotional journey of motherhood — before, during, and long after. We shed the performance of perfect mothering and simply be: honest, raw, supported.",
    schedule: "Every Saturday",
    time: "10:00 – 11:30 AM EAT",
    nextSession: "Saturday, 14 June",
    format: "Video Call",
    duration: "90 min",
    members: 16,
    maxMembers: 20,
    status: "upcoming",
    color: "#D4A5A5",
    secondaryColor: "#A06060",
    icon: "🌸",
    tags: ["Motherhood", "Postpartum", "Spirituality", "Wellness"],
    joined: "2026-05-20",
    sessionsAttended: 2,
    totalSessions: 3,
    price: "free",
    upcomingTopics: ["Releasing the 'perfect mother' myth"],
    resources: ["Postpartum affirmation cards"],
    level: "Mothers only",
  },
  {
    id: 4,
    name: "Men Who Feel",
    category: "Men's Wellness",
    facilitator: "Jabari Ndung'u",
    facilitatorTitle: "Counselling Psychologist",
    tagline: "Strength looks like honesty here.",
    description:
      "A private, judgment-free circle for men ready to explore their emotional worlds. We unlearn silence and rediscover what it means to be whole — not just functional.",
    schedule: "Every Wednesday",
    time: "8:00 – 9:30 PM EAT",
    nextSession: "Wednesday, 11 June",
    format: "Video Call",
    duration: "90 min",
    members: 8,
    maxMembers: 12,
    status: "active",
    color: "#9BB3C8",
    secondaryColor: "#4A6A88",
    icon: "🌊",
    tags: ["Men", "Emotions", "Vulnerability", "Growth"],
    joined: "2026-05-01",
    sessionsAttended: 2,
    totalSessions: 4,
    price: "free",
    upcomingTopics: ["Emotional vocabulary", "Asking for help"],
    resources: ["Feelings wheel", "Self-compassion for men guide"],
    level: "Men only",
  },
  {
    id: 5,
    name: "Releasing Anxiety",
    category: "Mental Health",
    facilitator: "Dr. Amara Diallo",
    facilitatorTitle: "Clinical Psychologist",
    tagline: "Your nervous system deserves peace.",
    description:
      "A science-informed, spiritually aware group for those living with anxiety. We combine evidence-based tools with breathwork and community support to help your body remember safety.",
    schedule: "Every Monday",
    time: "7:00 – 8:00 PM EAT",
    nextSession: "Monday, 9 June",
    format: "Video Call",
    duration: "60 min",
    members: 19,
    maxMembers: 20,
    status: "filling",
    color: "#B8A8D4",
    secondaryColor: "#6A5A94",
    icon: "🌙",
    tags: ["Anxiety", "Nervous System", "Breathwork", "CBT"],
    joined: "2026-05-25",
    sessionsAttended: 1,
    totalSessions: 8,
    price: "free",
    upcomingTopics: ["Worry habits", "Grounding techniques"],
    resources: ["Anxiety tracking sheet", "Calm breath audio"],
    level: "All are welcome",
  },
  {
    id: 6,
    name: "Spiritual Seekers Circle",
    category: "Spirituality",
    facilitator: "Zara Kamau",
    facilitatorTitle: "Spiritual Director",
    tagline: "For those asking the deeper questions.",
    description:
      "An interfaith circle for those exploring purpose, faith, and spiritual identity. We welcome doubt, wonder, and every stage of the journey. No theology required — only openness.",
    schedule: "Every Sunday",
    time: "5:00 – 6:30 PM EAT",
    nextSession: "Sunday, 15 June",
    format: "Video Call",
    duration: "90 min",
    members: 12,
    maxMembers: 20,
    status: "active",
    color: "#C8C8A8",
    secondaryColor: "#888860",
    icon: "✨",
    tags: ["Spirituality", "Faith", "Purpose", "Interfaith"],
    joined: "2026-06-01",
    sessionsAttended: 1,
    totalSessions: 6,
    price: "free",
    upcomingTopics: ["What is sacred to you?", "Doubt as a teacher"],
    resources: ["Journal prompts for seekers", "Meditation for openness"],
    level: "All are welcome",
  },
];
